// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace TransportSystemASP.Models;

public partial class DriverPermit
{
    public int PermitId { get; set; }

    public int DriverId { get; set; }

    public int RouteId { get; set; }

    public string PermitNumber { get; set; }

    public DateTime IssueDate { get; set; }

    public DateOnly ExpiryDate { get; set; }

    public virtual Driver Driver { get; set; }

    public virtual Route Route { get; set; }
}