// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace TransportSystemASP.Models;

public partial class Driver
{
    public int DriverId { get; set; }

    public string FullName { get; set; }

    public string Phone { get; set; }

    public int? ExperienceYears { get; set; }

    public virtual ICollection<DriverPermit> DriverPermits { get; set; } = new List<DriverPermit>();

    public virtual ICollection<Order> Orders { get; set; } = new List<Order>();
}