// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace TransportSystemASP.Models;

public partial class Order
{
    public int OrderId { get; set; }

    public int UserId { get; set; }

    public int DriverId { get; set; }

    public int VehicleId { get; set; }

    public int RouteId { get; set; }

    public DateOnly OrderDate { get; set; }

    public decimal? CargoWeight { get; set; }

    public string Status { get; set; }

    public virtual Driver Driver { get; set; }

    public virtual Route Route { get; set; }

    public virtual User User { get; set; }

    public virtual Vehicle Vehicle { get; set; }
}