// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace TransportSystemASP.Models;

public partial class Route
{
    public int RouteId { get; set; }

    public string StartPoint { get; set; }

    public string EndPoint { get; set; }

    public decimal? Distance { get; set; }

    public virtual ICollection<DriverPermit> DriverPermits { get; set; } = new List<DriverPermit>();

    public virtual ICollection<Order> Orders { get; set; } = new List<Order>();
}