// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;

namespace TransportSystemASP.Models;

public partial class TransportSystem2Context : DbContext
{
    public TransportSystem2Context(DbContextOptions<TransportSystem2Context> options)
        : base(options)
    {
    }

    public virtual DbSet<Driver> Drivers { get; set; }

    public virtual DbSet<DriverPermit> DriverPermits { get; set; }

    public virtual DbSet<Order> Orders { get; set; }

    public virtual DbSet<Route> Routes { get; set; }

    public virtual DbSet<User> Users { get; set; }

    public virtual DbSet<Vehicle> Vehicles { get; set; }

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.Entity<Driver>(entity =>
        {
            entity.HasKey(e => e.DriverId).HasName("PK__Drivers__F1B1CD24FAFF1E6A");

            entity.Property(e => e.DriverId).HasColumnName("DriverID");
            entity.Property(e => e.FullName)
                .IsRequired()
                .HasMaxLength(100);
            entity.Property(e => e.Phone).HasMaxLength(20);
        });

        modelBuilder.Entity<DriverPermit>(entity =>
        {
            entity.HasKey(e => e.PermitId).HasName("PK__DriverPe__0B0E6DB054D7CFF6");

            entity.HasIndex(e => new { e.DriverId, e.RouteId }, "UQ_Driver_Route").IsUnique();

            entity.Property(e => e.PermitId).HasColumnName("PermitID");
            entity.Property(e => e.DriverId).HasColumnName("DriverID");
            entity.Property(e => e.PermitNumber)
                .IsRequired()
                .HasMaxLength(50);
            entity.Property(e => e.RouteId).HasColumnName("RouteID");

            entity.HasOne(d => d.Driver).WithMany(p => p.DriverPermits)
                .HasForeignKey(d => d.DriverId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__DriverPer__Drive__4222D4EF");

            entity.HasOne(d => d.Route).WithMany(p => p.DriverPermits)
                .HasForeignKey(d => d.RouteId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__DriverPer__Route__4316F928");
        });

        modelBuilder.Entity<Order>(entity =>
        {
            entity.HasKey(e => e.OrderId).HasName("PK__Orders__C3905BAFE409E493");

            entity.Property(e => e.OrderId).HasColumnName("OrderID");
            entity.Property(e => e.CargoWeight).HasColumnType("decimal(10, 2)");
            entity.Property(e => e.DriverId).HasColumnName("DriverID");
            entity.Property(e => e.RouteId).HasColumnName("RouteID");
            entity.Property(e => e.Status).HasMaxLength(50);
            entity.Property(e => e.UserId).HasColumnName("UserID");
            entity.Property(e => e.VehicleId).HasColumnName("VehicleID");

            entity.HasOne(d => d.Driver).WithMany(p => p.Orders)
                .HasForeignKey(d => d.DriverId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__Orders__DriverID__46E78A0C");

            entity.HasOne(d => d.Route).WithMany(p => p.Orders)
                .HasForeignKey(d => d.RouteId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__Orders__RouteID__48CFD27E");

            entity.HasOne(d => d.User).WithMany(p => p.Orders)
                .HasForeignKey(d => d.UserId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__Orders__UserID__45F365D3");

            entity.HasOne(d => d.Vehicle).WithMany(p => p.Orders)
                .HasForeignKey(d => d.VehicleId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__Orders__VehicleI__47DBAE45");
        });

        modelBuilder.Entity<Route>(entity =>
        {
            entity.HasKey(e => e.RouteId).HasName("PK__Routes__80979AADFBD56AF8");

            entity.Property(e => e.RouteId).HasColumnName("RouteID");
            entity.Property(e => e.Distance).HasColumnType("decimal(10, 2)");
            entity.Property(e => e.EndPoint).HasMaxLength(100);
            entity.Property(e => e.StartPoint).HasMaxLength(100);
        });

        modelBuilder.Entity<User>(entity =>
        {
            entity.HasKey(e => e.UserId).HasName("PK__Users__1788CCACA8A6E55B");

            entity.HasIndex(e => e.Login, "UQ__Users__5E55825B0B1B0A92").IsUnique();

            entity.Property(e => e.UserId).HasColumnName("UserID");
            entity.Property(e => e.FullName)
                .IsRequired()
                .HasMaxLength(100);
            entity.Property(e => e.Login)
                .IsRequired()
                .HasMaxLength(50);
            entity.Property(e => e.PasswordHash)
                .IsRequired()
                .HasMaxLength(255);
            entity.Property(e => e.Role)
                .IsRequired()
                .HasMaxLength(20);
        });

        modelBuilder.Entity<Vehicle>(entity =>
        {
            entity.HasKey(e => e.VehicleId).HasName("PK__Vehicles__476B54B2AB050270");

            entity.HasIndex(e => e.NumberPlate, "UQ__Vehicles__94853CA050539C06").IsUnique();

            entity.Property(e => e.VehicleId).HasColumnName("VehicleID");
            entity.Property(e => e.Brand).HasMaxLength(50);
            entity.Property(e => e.Capacity).HasColumnType("decimal(10, 2)");
            entity.Property(e => e.Model).HasMaxLength(50);
            entity.Property(e => e.NumberPlate)
                .IsRequired()
                .HasMaxLength(20);
        });

        OnModelCreatingPartial(modelBuilder);
    }

    partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
}