// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace TransportSystemASP.Models;

public partial class User
{
    public int UserId { get; set; }

    public string FullName { get; set; }

    public string Login { get; set; }

    public string PasswordHash { get; set; }

    public string Role { get; set; }

    public virtual ICollection<Order> Orders { get; set; } = new List<Order>();
}