// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace TransportSystemASP.Models;

public partial class Vehicle
{
    public int VehicleId { get; set; }

    public string Brand { get; set; }

    public string Model { get; set; }

    public string NumberPlate { get; set; }

    public decimal? Capacity { get; set; }

    public virtual ICollection<Order> Orders { get; set; } = new List<Order>();
}